#cloud-config

packages:
- haproxy

write_files:
  - path: /etc/haproxy/haproxy.cfg
    owner: roor:root
    defer: true
    content: |
      global
        daemon
        group  haproxy
        log  /dev/log local0
        maxconn  10000
        pidfile  /var/run/haproxy.pid
        user  haproxy

      defaults
        log  global
        mode  tcp
        retries  3
        timeout  http-request 10s
        timeout  queue 1m
        timeout  connect 10s
        timeout  client 1m
        timeout  server 1m
        timeout  check 10s

      frontend terraform-balancer_12345678
        bind *:80
        mode http
        default_backend terraform-balancer_12345678

      backend terraform-balancer_12345678
        mode http
        option forwardfor
        balance roundrobin
        #cookie MYCOOKIE insert indirect nocache maxidle 20s maxlife 20s
        cookie session prefix indirect nocache
        server app1 192.168.2.100:80 weight 1 maxconn 512 cookie 1 check
        server app2 192.168.2.200:80 weight 1 maxconn 512 cookie 2 check

runcmd:
- [ systemctl, restart, haproxy.service]