#cloud-config

packages:
- python3.9

write_files:
  - path: /home/outscale/webapp/main.py
    owner: root:root
    permissions: 0o600
    defer: true
    content: |
      from flask import Flask, session

      from flask_session import Session
      
      app = Flask(__name__)
      app.config.update(
          DEBUG = True,
          SESSION_TYPE = "filesystem",
          PERMANENT_SESSION_LIFETIME = 10,
      )
      Session(app)

      @app.route("/")
      def index():
          session.permanent = True
          session["name"] = "my_session_1"
          return "Congratulations, it's a web app AAA!"

  - path: /home/outscale/webapp/app.yml
    owner: root:root
    permissions: 0o600
    defer: true
    content: |
      runtime: python39
  - path: /home/outscale/webapp/requirements.txt
    owner: root:root
    permissions: 0o600
    defer: true
    content: |
      Flask>=2.2
      Flask-Session>=0.5.0
      gunicorn>=21.2.0


runcmd:
- rpm -Uvh https://s3.amazonaws.com/aaronsilber/public/authbind-2.1.1-0.1.x86_64.rpm
- touch /etc/authbind/byport/80
- chmod 777 /etc/authbind/byport/80
- cd /home/outscale/webapp
- python3.9 -m venv venv
- source venv/bin/activate
- [ pip, install, -r, requirements.txt ]
- chown -R outscale:outscale /home/outscale/webapp/
- authbind --deep gunicorn main:app -b 0.0.0.0:80 --log-level debug --reload &
- deactivate


